name: Clear Token

on:
  [push, workflow_dispatch]

jobs:

  build:  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          
      - name: execute py script # run main.py
        run: |
          echo "Clearing token!"
          python .cleartoken.py

      - name: Create Hello.txt
        run: echo "Hallo" >> Hallo.txt

      - name: Commit report
        run: |
          git add *
          git config --global user.name 'Frank'
          git config --global user.email 'frank@inter-zone.de'
          git commit --allow-empty -am "Actions Commit %COMMIT"
          git push
        env: 
          COMMIT: ${{ github.event.head_commit.message }}
